[package]
name = "starter"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = "0.11.1"
serde = "1.0"
chrono = "0.4"
rand = "0.8.5"
hex = "0.3.1"
bitcoin_hashes = "0.11"
